# Generated by Django 4.2.30 on 2026-05-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=200, unique=True)),
                ('name_bn', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=200, unique=True)),
                ('name_bn', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hospital_affiliation',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='qualification',
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_affiliations',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='profiles.hospital'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualifications',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='profiles.qualification'),
        ),
    ]
